server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz99tyk065h7mj4q5bo.mysql.rds.aliyuncs.com/test_all_green?characterEncoding=utf-8
#    url: jdbc:mysql://127.0.0.1:3306/test_all_green?characterEncoding=utf-8
    username: root
    password: roottest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  banner:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
#  h2:
#    console:
#      enabled: true

pay:
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    appid: 2016092500597072
    appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCg/Pa9Ug7XxkQs2tfLDT9yxg32p8pbJfe3jWID1o5p4egQRjc/WNILtt4M9gD3ruox1bmI0QMnGCj0h78val0dxX/fnnLvYPzgg2ZMpIlrl9qfg3lbPSfbbZZYeNlX17XFyTFOul0JHBg7R4eBg4+J56zkIfcLT8V0SgbEQ4AY+H+wbi3e08gpjWtjWLyFipT0SoShByBm/JAcQbZGgkTy5DSpXDph5sIyD5t/Dfx/TxJ7/mmDLnO6eBNxjmO+XTYgH4YYkryeE49FN79vPppJjbT4C4HyU18p8U0ftQ4Fg/aN8z2szQPFsl5szdGxJlF3HO0xTUu9jbpLvbMVgXJbAgMBAAECggEAOW1DTxGAffQZya5fH+2f3n9L59q+0njevrlOZ3QX5SlSsMt7VbuHYepfl1wByFi67gABaQ62AzIZGfF6f51/jekvzkMlWMLOMgBtc5WV9615rUEm/yb3msyivviM/0rRarZ0QlM0cNV2x16itc6KW3UrNU3wZDaWhv8JHuW9Qip/5UXpP/oAiDggU/413a9bV6jidMJliP2sFf/E6go3/HlGEvAR5VB1SDN5UtR8yMcjeyrifN+wU34i1aMs6d2ok8Qbh0JsLrS76EM8qxBij0V2hNAfMWktj0A3jM5Iks1nNfrkMOVQcduenoI/C9jdUtIyw889VouoVPdU34I9wQKBgQDwjOburyoOkTwd/HkszRyoQ20o7CgRGJxxsUEwmkv0gR2TZngHhARBFamIUT23XZkTwcHdnRYdyak+aKqf/Bx9ED1lGz5Y7ZRz1U8WDXQtiKZTcKhPU6NeYYI2gRZrPue4Gzvprqq6puSQMYVTVDXf8BzlMofoK1PaQJIcOsuPMQKBgQCrU+jagkJ03hCZ21CMw9OOOJUP3hRdCg2gzD5neTFG2CCG+lUAU30phZo/hmenTLmmT2C7CEIyeFkGAfgJ9jesRzgvc3xXw1I/UmVPwpTQwceVRxnqyjj1+yiwoz4ac9jSX67fWcXZWNc3v7VpbLsUeUYCXdfLiYra7xM3HbyvSwKBgEZGQ6jzT2wWDeQMwDHQclDN8fQEmef0sq+cQxk52nrBxawsQWCgtsV02KRUZ51MIM5eyo49uBpXsbPjzAUVGBWJSwZgoSRFtBrq9EHTCF/NDhpOTT1vh8io3+ugZrZKGFP20NgCCSqiWx+s9/BSJ7MWaLqkuoOfNM4MEyNgIdvhAoGADA8y87Z5gQpkdr/2MoJSMM+QxnYmTso3XVsjBVuFeWwbFgUm2IgH5lVOHyyRvTfsVWV+9ItHRZAtC/w1flYDYy/8J3LkjLTl5CkjknKq0Ori5oIDtAAZ9E6CdbR32ZrP5zbu8y+5emwDchwfY9VQccd7gw0h9GSxDmoHmziPoHMCgYB42cBGcWVMhaWOve5RvEA9wZQxMv/tNujm6Mpd57OQI++jcq/PICxw3gCYvqPHwGoyJgarFgTrWgZ97j7kwnz7BRHweNNyPnCmfv0u7oQsqwwfgzW8CHnA1Na3g1yW5VhwCsDEMTDAjDMXByIEn9Nlz12HeIaZR3KCZJ9FYHWIJg==
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxkArn8zDAdiHTE2ehEJSAoThJh/Xg3hDH7ImABFfrwb1oTuzoK0pwGeMO/VYKcdEWSeAsnPxU0fpL3FwUJjcyjDjCa/a1Oaj9YRjBwBt1fMbsKLRgI0DUdVTaLBryO/VEvHgxVBxBCOGhbHx+hi0pp+AFufE/w9IBz+JR0MNa7f8GtFoVEmciHyMFi3UKi+AoMexzUS8ykqMXGmzbc8jR3tBCh6UG8CShycPMzGdY4B7NIuAIqFCW+zLOvo7H3XdvTqMqMjxwa8bvzY8y53SuyeCve0jNYo0tqCmSkIP2sZB7OXnmizKEhNSKjNmM7jmBnCSrVne2V2W/PpK4L9vjQIDAQAB
    returnUrl: http://39.98.243.100:8081/custom/order
    notifyUrl: http://39.98.243.100:8081/custom/order
